model: "pt_spike_mamba"
trans_dim: 384
depth: 12
drop_path_rate: 0.1
rms_norm: False
use_cls_token: False
drop_path: 0.2
drop_out: 0.
fetch_idx: [3, 7, 11]
spike_mode: "lif"
timestep: 2
expand: 1.1  # Q-SDE++ hyper-parameter